### ISSUE TITLE
Install the PlantUML extension

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#11]
Source: https://github.com/pjkersten/PlantUML

**Comment by JeroenDeDauw** [comment]
https://github.com/pjkersten/PlantUML/tree/master/tests :D

**Comment by mwjames** [comment]
Do we really need this? Who is using it? Not saying it shouldn't be installed but just wondering about its use since smw.org hardly sees any docu changes, and I can't imagine that this will pull more volunteers to improve the documentation.

**Comment by kghbln** [comment]
Well, we leaped directly into reality here is several respects. If this triggers engagement we are currently not seeing ...

**Comment by WolfgangFahl** [comment]
@mwjames  I am an example of a volunteer who would do much more work with PlantUML than without it.

**Comment by kghbln** [comment]
This was installed long ago on sandbox and will continue to be present on the wiki. It will however not make it to www.
