### ISSUE TITLE
Allow abitrary titles for `DISPLAYTITLE`

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#12]
DISPLAYTITLE on Help: namespace seems disabled

**Comment by mwjames** [comment]
https://www.semantic-mediawiki.org/wiki/Help:Setting_values/Working_with_the_separator_parameter/Example_for_setting_multiple_values_using_the_sep_parameter

**Comment by kghbln** [comment]
That's a core namespace which afaik cannot be disabled and actually [it is not](https://www.semantic-mediawiki.org/w/index.php?title=Special%3APrefixIndex&prefix=&namespace=12). To resolve this issue [`$wgRestrictDisplayTitle`](https://www.mediawiki.org/wiki/Manual:$wgRestrictDisplayTitle) must be set to "false".

**Comment by kghbln** [comment]
Done!

**Comment by mwjames** [comment]
Much appreciate the swift service.
