### ISSUE TITLE
Define a fixed property for testing purposes

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#14]
See [fixed property](https://www.semantic-mediawiki.org/wiki/Help:Fixed_properties)

**Comment by kghbln** [comment]
I have just added the following to "LocalSettings.php":

``` php
$smwgFixedProperties = array(
    'Has_text_fixed' => SMWDataItem::TYPE_BLOB,
    'Has_page_fixed' => SMWDataItem::TYPE_WIKIPAGE
);
```

"update.php":

```
Checking table smw_fpt_52dba83206b2ebe999cf91202670670c ...
   Table not found, now creating...
   ... done.
Checking index structures for table smw_fpt_52dba83206b2ebe999cf91202670670c ...
   ... creating new index s_id ...done.
   ... creating new index o_hash ...done.
   ... creating new index s_id,o_hash ...done.
   ... done.
Checking table smw_fpt_867717396665080354b2999bcbf690c2 ...
   Table not found, now creating...
   ... done.
Checking index structures for table smw_fpt_867717396665080354b2999bcbf690c2 ...
   ... creating new index s_id ...done.
   ... creating new index o_id ...done.
   ... done.
```

This is obviously an unused feature since the result is not very encouraging: [test page](http://sandbox.semantic-mediawiki.org/wiki/Fixed_properties), [test page - browse](http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/Fixed_properties)

That's probably another front.

**Comment by kghbln** [comment]
FYI @mwjames @JeroenDeDauw I guess findings should be reported as bugs.

**Comment by kghbln** [comment]
I have to pull this. "rebuildData.php" fails and tells me to add `$wgShowExceptionDetails = true;` to find out more. However, this is already set. Let's postpone this to [SMW 3.0](https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestone/6)

**Comment by mwjames** [comment]
> However, this is already set. Let's postpone this to 3.0

Yes

PS: `SMWDataItem::TYPE_BLOB` I don't like the binding of an internal data object in a settings file! What happens when the property page says `[[Has type::Page]]` and you make it a fixed `SMWDataItem::TYPE_BLOB`, this smells.

**Comment by kghbln** [comment]
Just gave https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2135 a shot and defined [them on sandbox](https://sandbox.semantic-mediawiki.org/w/index.php?title=SMW_Sandbox%3ASetup_information&type=revision&diff=5294&oldid=4859). "rebuildData.php" did not show any issues either. Utterly cool!
