### ISSUE TITLE
"Über Finland diskutieren" ?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#15]
@kghbln Something is wrong here, all of the sudden in different places all page titles contain "Über Finland diskutieren".

Special:RecentChanges (which SMW does nothing)

![image](https://cloud.githubusercontent.com/assets/1245473/18332950/05fe313e-756b-11e6-8fd8-71e61cfead89.png)

Special:Browse

![image](https://cloud.githubusercontent.com/assets/1245473/18332967/25b1c04a-756b-11e6-9649-51125363d9a0.png)

**Comment by mwjames** [comment]
Adding a simple `[[Page A]]` link to [0] turns into "Über Finland diskutieren".

[0] http://sandbox.semantic-mediawiki.org/wiki/Issue/1823/Page_B

**Comment by mwjames** [comment]
Categories [0] appear as:

![image](https://cloud.githubusercontent.com/assets/1245473/18333750/0ea0d63c-7572-11e6-86d1-6b368e0e78c4.png)

[0] http://sandbox.semantic-mediawiki.org/wiki/Berlin

**Comment by kghbln** [comment]
Admittedly I am completely lost as to what may cause this. I have not touched the wiki in weeks. Still need to figure out there to start looking for the issue.

**Comment by kghbln** [comment]
Since this started yesterday or the day before these are the changes what may have caused this:

[04.09.](https://wikiapiary.com/w/index.php?title=Semantic_MediaWiki_-_Sandbox/Extensions&diff=3048015&oldid=3044945)
[07.09.](https://wikiapiary.com/w/index.php?title=Semantic_MediaWiki_-_Sandbox/Extensions&diff=3050375&oldid=3048015)

**Comment by mwjames** [comment]
Last changes on SMW were merged on Sep 1, 2016 [0] and after that (except for today) only relates to https://translatewiki.net.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/97260f3c2789b3224fedbdf60ceee2a43ad26c54

**Comment by mwjames** [comment]
Also SMW doesn't touch anything in regards to `Special:RecentChanges`, I'm guessing "Über Finland diskutieren" to be German but this doesn't make any sense. Not sure how [0] fits into this.

[0] http://sandbox.semantic-mediawiki.org/wiki/Discussion:Q33

**Comment by kghbln** [comment]
> Also SMW doesn't touch anything in regards to Special:RecentChanges, I'm guessing "Über Finland diskutieren" to be German but this doesn't make any sense. Not sure how [0] fits into this.

It however provides a clue about what happens. The user mentioned that "Finland" (in English) being shown all over the place. This is happening because you added a page on 02.09. with the displaytitle "Finland". After this persons edit it changed to "Über Finnland diskutieren" (in German) because this user's personal language setting is probably German (still need to confirm) and now that I have answered to it all of the sudden things change to "Discuss Finland" (in English) because my personal language setting is English. Since we are working on the page about Finland and discussing it I can see a scheme.

**Comment by mwjames** [comment]
Grasping at straws now:

> It however provides a clue about what happens.

What about creating another page X, add a DISPLAYTITLE, and then create a Talk tread to that page?

What about disabling DISPLAYTITLE related settings temporary and see whether this changes things or not.

```
$wgAllowDisplayTitle = true;
$wgRestrictDisplayTitle = false;
```

**Comment by kghbln** [comment]
This is producing inconsistent behaviour with settings on and off. I will have to figure out a testing procedure.

**Comment by mwjames** [comment]
It seems that the issue can only be observed for red links (page not created, user not created, or category not created as "real" page)

**Comment by kghbln** [comment]
> It seems that the issue can only be observed for red links

Indeed this is also my observation. Still there is something in the water we have not seen yet.

**Comment by mwjames** [comment]
It still doesn't explain where the "Über Finland diskutieren" comes from. Maybe some Title cache issue?

**Comment by mwjames** [comment]
Hooks (only on a quick scan) that can manipulate the output characteristics of a link (not used by SMW)  are:
- https://www.mediawiki.org/wiki/Manual:Hooks/LinkBegin
- https://www.mediawiki.org/wiki/Manual:Hooks/LinkEnd

Also, the `refreshLinks` job [0] maybe a potential candidate on using an outdated cache entry when update links.

[0] https://www.mediawiki.org/wiki/Manual:RefreshLinks.php as to "... script purges those links, which point to non-existing pages, from the tables pagelinks, imagelinks, categorylinks, templatelinks, externallinks, iwlinks, langlinks, redirect, and page_props ..."

**Comment by mkroetzsch** [comment]
How curious! Unfortunately, I cannot provide any suggestions. I have never seen such behaviour and have no clue what might be causing it.

The text is inserted for both non-existing pages and for existing special pages, but not for existing regular pages. Message pages behave like normal pages. See http://sandbox.semantic-mediawiki.org/wiki/Tests2143234

**Comment by kghbln** [comment]
I wonder what could have caused this. I just ran "refreshLinks.php" with visible success on the wiki. His is the interesting part of the scripts output:

```
Deleting illegal entries from the links tables...
  Checking interval (-INF, INF)
    pagelinks: 0 deleted.
    imagelinks: 0 deleted.
    categorylinks: 0, 2 deleted.
    templatelinks: 0, 2 deleted.
    externallinks: 0 deleted.
    iwlinks: 0 deleted.
    langlinks: 0 deleted.
    redirect: 0 deleted.
    page_props: 0, 3 deleted.
```

I left the settings unchanged.

**Comment by kghbln** [comment]
The wiki continuous to be fluffy. Keeping fingers crossed. Closing this for now.
