### ISSUE TITLE
Update wiki to use the MW 1.28 branch

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#17]
Now that [MW 1.28.0-rc0](https://lists.wikimedia.org/pipermail/mediawiki-announce/2016-November/000201.html) is available.

REM: $wgPingback

**Comment by kghbln** [comment]
Done! Everything went smooth. Let's see what happens on the wiki.

**Comment by kghbln** [comment]
Interesting: 
- Size of the DB-dump prior to the update: 16,2 MB
- Size of the DB-dump after the update: 10,4 MB

That's quite a big difference. Do these three make it?:

```
Checking index structures for table smw_ft_search ...
   ... index s_id is fine.
   ... index p_id is fine.
   ... index o_sort is fine.
   ... removing index o_text ...done.
   ... creating new index o_text ...done.
   ... done.

Checking index structures for table smw_prop_stats ...
   ... removing index p_id ...done.
   ... index usage_count is fine.
   ... creating new index p_id ...done.
   ... done.

Removing empty categories without description pages...
--mode=remove --begin=Testpage
Category cleanup complete.
Removing orphaned echo_event rows...
Deleted 500 orphaned rows.
Deleted 1000 orphaned rows.
Deleted 1500 orphaned rows.
Deleted 1584 orphaned rows.
```

This is just to remember. Well if everything remains fluffy on the wiki ...

**Comment by mwjames** [comment]
:+1: 

>    ... removing index p_id ...done.
>   ... index usage_count is fine.

I think those lines are suspicious hence https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1978.

>  Size of the DB-dump prior to the update: 16,2 MB
>  Size of the DB-dump after the update: 10,4 MB

I'm guessing `Removing orphaned echo_event rows...` to be responsible here.

**Comment by kghbln** [comment]
> I think those lines are suspicious hence SemanticMediaWiki/SemanticMediaWiki#1978.

Good that I cared to note this. Thanks for the fix!

> I'm guessing Removing orphaned echo_event rows... to be responsible here.

Rhetorically spoken I wonder what Echo stored there.  36 % ot the database size sounds like heaps of stuff to me.
