### ISSUE TITLE
Unable to read pages

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/semantic-mediawiki.org#18]
For example https://www.semantic-mediawiki.org/wiki/Help:User_manual?uselang=en gives

```
You do not have permission to read this page, for the following reason:

You must confirm your email address before editing pages. Please set and validate your email address through your user preferences.
```

This applies to all pages.

**Comment by kghbln** [comment]
@Nikerabbit A bug in 1.27.1 and a misconfiguration at once. Did not see this since I was logged in. Fixed! Thanks for noticing and reporting!
