### ISSUE TITLE
TOC display distorted

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#19]
Since the upgrade to 1.27 the TOC display is distorted.

![image](https://cloud.githubusercontent.com/assets/1245473/20235602/943d9422-a896-11e6-80de-c4a223b0ab9c.png)

https://www.semantic-mediawiki.org/wiki/Help:Installation

**Comment by kghbln** [comment]
Yeah, seen this too. Something with the `smworgtable-toc` did not make it to Vector.

**Comment by kghbln** [comment]
Just removed the [transgressing CSS](https://www.semantic-mediawiki.org/w/index.php?title=MediaWiki%3ACommon.css&type=revision&diff=47225&oldid=47128)!
