### ISSUE TITLE
Fix semanticmediawiki.org

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#2]
"semanticmediawiki_org" should redirect to "www.semantic-mediawiki_org".

Originally reported as [issue 1528](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1528)

**Comment by mkroetzsch** [comment]
<strike>Works for me.</strike> I am not in charge of `semanticmediawiki.org`, only of  `semantic-mediawiki.org`, which works as it should.

**Comment by kghbln** [comment]
Up till now I expected "semanticmediawiki_org" to be at Hetzner somewhere. Apparently the whois says that it is with Frank at antagus. We got this domain about one and a half years ago from Sergey. No sure why it ended up there.

**Comment by kghbln** [comment]
Finally done. @JeroenDeDauw switched the IP from 78.47.80.197 (old server) to 78.47.118.255 (new server), it actually was at Hetzner, and I just added the vhost for the domain redirecting to s-mw.o
