### ISSUE TITLE
JavaScript of the info box for result formats failing

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#20]
Most probably since the update to MW 1.27.x the respective script ["tab/panel right slide"](https://www.semantic-mediawiki.org/wiki/MediaWiki:Common.js) fails, at least on recent Fx and Ch:

```js
/**
 * Tab/Panel right slide
 * @author mwjames
 */

$("#panel-tab").click( function (event) {
	event.stopPropagation();
	showIfNotVisible( "#panel-content" );
} );

function showIfNotVisible( element ) {
	var width = $( '#panel' ).find( 'table').width() + 8; 
	if ( $(element).css( "width" ) == width + 'px' )
		$(element).animate( { width: 4 }, 1500);
	else
		$(element).animate( { width: width }, 1500);
};

$( function() {
	var element = $("#panel-content"),
	status = element.attr( 'class' ),
	width = element.find( 'table').width() + 8;

	if ( status === 'close' ){
		element
		.width( width )
		.animate( { width: 4 }, 1200);
	} else {
		element
		.width( width );
	}
} );
```
@mwjames It will be great if you could have a peep at this.

**Comment by kghbln** [comment]
I do not know why but all JavaScript seems to be broken, e.g. the SMWAgenda buttons too. Of course without emitting any error in console. That's pretty discouraging. Probably we should just kick all of this magic.

**Comment by kghbln** [comment]
Indeed removing some code [of unknown purpose](https://www.semantic-mediawiki.org/w/index.php?title=MediaWiki%3ACommon.js&type=revision&diff=47496&oldid=45714) fixed the issue. Thanks @mwjames 

Still keeping this open until I have worked on this agenda stuff.

**Comment by mwjames** [comment]
> Indeed removing some code of unknown purpose fixed the issue.

`debug=true` added to an URL revealed:

![image](https://cloud.githubusercontent.com/assets/1245473/20313075/013ce66a-ab56-11e6-834b-75a62672dda3.png)

**Comment by kghbln** [comment]
> debug=true added to an URL revealed:

Ah, good idea. Still do not know what these edit buttons were all about. Also just remove the SMWCon Agenda button magic which provided a appearance change when hovering. Tought titties they say.
