### ISSUE TITLE
link Page Schemas tutorial from Main_Page

### ISSUE THREAD

**Issue by TomRoche** [SemanticMediaWiki/semantic-mediawiki.org#21]
For reasons described [here](https://sandbox.semantic-mediawiki.org/wiki/Create_datastructures_from_Page_Schemas#why_Page_Schemas.3F), I wanted to verify functionality now that [Page Schemas](https://www.mediawiki.org/wiki/Extension:Page_Schemas) has been installed on the sandbox. (Thanks, KGH!) I was able to work through an example, which I subsequently documented as a tutorial for [creating datastructures from Page Schemas](https://sandbox.semantic-mediawiki.org/wiki/Create_datastructures_from_Page_Schemas). I believe this tutorial may be useful to OP; [YMMV](https://en.wiktionary.org/wiki/YMMV), but if you agree, please link it into the sandbox main page, in (e.g.) [section=`Extension related examples`](https://sandbox.semantic-mediawiki.org/wiki/Main_Page#Extension_related_examples). (I'm not seeing UI to do that, so am assuming I lack permissions.)

**Comment by kghbln** [comment]
Thank you for adding the tutorial and your suggestion! To keep the main page somewhat lean in the long term I extended the section now to be called ["Extension related examples and tutorials"](https://sandbox.semantic-mediawiki.org/w/index.php?title=Main_Page&type=revision&diff=4732&oldid=3642) and added the respective categorisation to your tutorial for quick access.
