### ISSUE TITLE
Set up pretty URIResolver

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#26]
Related documentation:
- https://www.semantic-mediawiki.org/wiki/Help:Pretty_URIs
- https://www.semantic-mediawiki.org/wiki/Help:$smwgNamespace

**Comment by kghbln** [comment]
Docu that also has to be updated:
* https://www.semantic-mediawiki.org/wiki/Help:Pretty_URIs

**Comment by kghbln** [comment]
> Docu that also has to be updated: https://www.semantic-mediawiki.org/wiki/Help:Pretty_URIs

[Done](https://www.semantic-mediawiki.org/w/index.php?title=Help%3APretty_URIs&type=revision&diff=51825&oldid=49803)

**Comment by kghbln** [comment]
What I have done:

Added the following lines to the VirtualHost on the respective spots:

```apache
Alias /wiki /var/www/html/02310/w/index.php
```
```apache
RewriteRule ^/id/(.*) /wiki/Special:URIResolver/$1 [L,P]
```

Added the following line to "LocalSettings.php" to the respective spots:

```php
$wgUsePathInfo = true;
```
Probably this setting is not needed since short URLs work without this setting which is only required under certain circumstances.
```php
$smwgNamespace = 'https://www.semantic-mediawiki.org/id/';
```

As a result "Special:RDFExport" adds:
```xml
<swivt:Subject rdf:about="https://www.semantic-mediawiki.org/id/Karlsruhe">
```
However https://www.semantic-mediawiki.org/id/Karlsruhe redirects to Main_Page since there is not accessible page at `id/Karlsruhe`. On the other hand https://www.semantic-mediawiki.org/wiki/Special:URIResolver/Karlsruhe redirects to https://www.semantic-mediawiki.org/wiki/Karlsruhe.

I am actually not sure what the expected behaviour of this setup is meant to be in the first place. As a human I still would like to access the Karlsruhe page via "https://www.semantic-mediawiki.org/wiki/Karlsruhe" instead of "https://www.semantic-mediawiki.org/id/Karlsruhe" no matter what we are doing here.

**Comment by kghbln** [comment]
@mwjames Hmm ...?

**Comment by kghbln** [comment]
I can imagine that I perhaps added the redirect rule too late meaning that the preceding ones already trigger the page to be delivered at  "https://www.semantic-mediawiki.org/wiki/Karlsruhe" instead of "https://www.semantic-mediawiki.org/id/Karlsruhe".

From my perspective the expected result should be that humans access via `/wiki/` while machines access via `/id/`.

**Comment by mwjames** [comment]
> @mwjames Hmm ...

Without having reviewed the content of the listed page, my
understanding is that:

The RDF export should point to ...id/Karlsruhe  and the rewrite rules
forward it to ...wiki/Special:URIResolver/Karlsruhe which is then
redirected to ...wiki/Karlsruhe.

The RDF should be canonical and stable hence the use of
...id/Karlsruhe which independent from whether the web server uses w,
wiki, or FOO as access point to a resource.

Special:URIResolver is responsible for "Resolve (redirect) pretty URIs
(or "short URIs") to the equivalent full MediaWiki representation."

Cheers

**Comment by kghbln** [comment]
@mwjames Thanks for the info. Now I understand the expected behaviour. So the first part is working and the third part. What is not working is the redirect to Special:URIResolver. I will have to investigate this.

**Comment by kghbln** [comment]
Yeah, something is borked, the rewrite rule 
```apache
RewriteRule ^/id/(.*) /wiki/Special:URIResolver/$1 [L,P]
``` 
has no effect whatsoever, even if I move it to the first position so it gets considered first. Since this tip is ten years old...

**Comment by mwjames** [comment]
On the http vs. https issue, remember that the RDF export can contain
resource links that may or may not exists in the "real" world and
therefore the protocol is not really important as long as the output
is stable.

The web server has to have some rules that forwards it to a matching
resource so that http://example/org/id/Foo and
https://example/org/id/Foo are equivalent, canonical, and protocol
agnostic.

In an ideal world http://example/org/id/Foo would always point to the
correct resource whether the underlying protocol is http, https, or
something entire different in future.

In a triple store <http://example/org/id/Foo> is used as identifier
and once you change the protocol in the export it becomes a different
entity and would result in a different matching scenario.

PS: Imagine a library would arbitrarily change its archive system with
the consequence that suddenly all references made invalid, the same
goes for the RDF export.

Cheers

**Comment by kghbln** [comment]
> On the http vs. https issue, [...] The web server has to have some rules that forwards it to a matching resource so that http://example/org/id/Foo and https://example/org/id/Foo are equivalent, canonical, and protocol agnostic.

Well this is certainly the case and additionally since `$wgServer` is not protocol relative `$wgCanonicalServer` does not need to be set.

> In a triple store <http://example/org/id/Foo> is used as identifier

Ah so back to what it was before on sandbox.

**Comment by mwjames** [comment]
>> In a triple store <http://example/org/id/Foo> is used as identifier
>
> Ah so back to what it was before on sandbox.

For a tangential reference point, see "Consider switching to HTTPS for
Wikidata query service links" [0].

[0] https://phabricator.wikimedia.org/T153563

**Comment by kghbln** [comment]
> For a tangential reference point, see "Consider switching to HTTPS for Wikidata query service links" [0].

The same battles all over the place. ;)

**Comment by kghbln** [comment]
The original idea to switch smw.o was to provide a wiki which uses this more compliant identifier and setup. However this results into different identifiers than before and since the redirect from the identifier is not even working at the moment. I still thing we should deliberately break to have a working example rather than having no example at all, i.e. revert to what it was before.

**Comment by kghbln** [comment]
I finally got this act together. It's backwards incompatible but what are ten years in comparison to the eons which still lay ahead.
