### ISSUE TITLE
Implement "mod_reqtimeout"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#3]
Thus it will be possible to serve a custom error page in case there is too much load on the server. See [comment on issue 1687](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1687#issuecomment-228160125)

**Comment by kghbln** [comment]
Let's see if this helps. Now added

``` apache
<IfModule mod_reqtimeout.c>
        RequestReadTimeout header=15-30,minrate=500
        RequestReadTimeout body=10,minrate=500
</IfModule>
```

I guess we still need a fancy ERROR 408 document.

**Comment by JeroenDeDauw** [comment]
![408](https://cloud.githubusercontent.com/assets/146040/16362308/0cd3cfee-3bac-11e6-90a1-68b60d5defa7.jpeg)

**Comment by kghbln** [comment]
Done on 2016-12-10 thought it appears to be a toothless tiger in the end.
