### ISSUE TITLE
Upgrade OS

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/semantic-mediawiki.org#30]
PHP7? - I see that ~both the main site and~ the sandbox are still running PHP 5.6. Any ETA on them switching to 7.x?

One reason of why I'm asking is that I'd like to do some work on the GitHub extension and bump it to 7.0+ at the same time.

**Comment by kghbln** [comment]
The release of Debian 9 is scheduled for [June 17, 2017](https://micronews.debian.org/2017/1495840892.html?utm_source=dlvr.it&utm_medium=twitter) which will ship with PHP 7.0 so I hope do upgrade the server this month.

**Comment by kghbln** [comment]
[instructions](https://linuxconfig.org/how-to-upgrade-debian-8-jessie-to-debian-9-stretch) not really different to the Debian 8 upgrade.

**Comment by kghbln** [comment]
>  I hope do upgrade the server this month.

Well, in the end I waited a bit longer for various reasons. However this is finally done now. And yes, thanks to Apache2 there were 30 minutes of extra downtime, because it was still trying to load php5. Unbelievable. I would never have guessed this.
