### ISSUE TITLE
Nabble stopped collecting mailing list posts

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#35]
This happened after August 22, 2017. Reported [upstream.](http://support.nabble.com/Collection-of-mailing-list-post-stopped-suddenly-td7598648.html)

@mwjames @JeroenDeDauw FYI

**Comment by JeroenDeDauw** [comment]
Maybe because they did not confirm they wanted to stay on the sourceforge mailing list?

**Comment by kghbln** [comment]
> Maybe because they did not confirm they wanted to stay on the sourceforge mailing list?

OMG, that may be the reason. So let's nabble fix this.

**Comment by kghbln** [comment]
Nabble has no intention to help here so I will have to migrate all the links on smw.o.

**Comment by JeroenDeDauw** [comment]
Migrate them to what?

**Comment by kghbln** [comment]
> Migrate them to what?

Currently back to the Sourceforge archive.
