### ISSUE TITLE
Close the IRC channel!

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#36]
Okay, seriously if no one answers the IRC channel then it should be scrapped as communication method. 

Looking at some of the unanswered calls, user have responded with "... I am wondering whether you can see my question?..." or "...this channel is just lame ;P"!

http://bots.wmflabs.org/~wm-bot/logs/%23semantic-mediawiki/20170915.txt

> [15:54:08] <traumschule>	 can sb help me to create a markers file like http://gapsinreality.com/nomadbases/maps/markers.json from semantic properties?
[15:54:51] <traumschule>	 the result formats list json but the opened file looks quite different https://www.semantic-mediawiki.org/wiki/Help:Result_formats
[20:21:56] <wikibugs>	 (PS1) Fz-29: Adding placeholder emulation for hierarchy structure textarea [extensions/PageForms] - https://gerrit.wikimedia.org/r/378277
[20:34:14] <traumschule>	 this channel is just lame ;P

http://bots.wmflabs.org/~wm-bot/logs/%23semantic-mediawiki/20170909.txt

> [02:34:39] <irl>=09
https://wiki.57north.org.uk/index.php?title=3DSpecial%3AAsk&q=3D%5B%5BCateg=
ory%3AEvents%5D%5D&po=3D&eq=3Dyes&p%5Bformat%5D=3Dbroadtable&sort_num=3D&or=
der_num=3DASC&p%5Blimit%5D=3D&p%5Boffset%5D=3D&p%5Blink%5D=3Dall&p%5Bsort%5=
D=3D&p%5Bheaders%5D=3Dshow&p%5Bmainlabel%5D=3D&p%5Bintro%5D=3D&p%5Boutro%5D=
=3D&p%5Bsearchlabel%5D=3D...+further+results&p%5Bdefault%5D=3D&p%5Bclass%5D=
=3Dsortable+wikitable+smwtable&p%5Bsep%5D=3D&eq=3Dyes
[02:35:19] <irl>=09 https://wiki.57north.org.uk/index.php/Category:Events
[03:55:12] <irl>=09 i see concepts didn't meant what i thought it meant,
still none of the queries are working

http://bots.wmflabs.org/~wm-bot/logs/%23semantic-mediawiki/20170907.txt

> [13:30:52] <traumschule>=09 hi. I am new to SMW, read many pages in the
wiki, but I am confused to select pages from a category via #ask not
showing images and category contenty.
[13:34:53] <traumschule>=09 {{#ask: |[[Category:fix]] |[[:+]] }} is a
workaround but it shows pages in selected categories as well

http://bots.wmflabs.org/~wm-bot/logs/%23semantic-mediawiki/20170906.txt

> [09:16:15] <Vahdati>=09 Hi all, I need /HELP
[09:19:02] <Vahdati>=09 we have a platform to manage CFPs using SMW,
suddenly list of Templates turned to Create Concept pages, the old
templates are working but I have no way to access them for edits and
also no way to create new templates, any ideas?
[09:19:47] <Vahdati>=09 here is the page:
http://openresearch.org/Special:Templates
[11:15:51] <Vahdati>=09 I am wondering whether you can see my question?

**Comment by kghbln** [comment]
After I [de-advertised the channel](https://www.semantic-mediawiki.org/w/index.php?title=Semantic_MediaWiki_chatroom&type=revision&diff=54164&oldid=52901) people indeed stopped using it. 

The examples you indicated tragically show how IRC can be misused as a forum for more or less complex issues which should go to the mailing list anyways. So basically we have three issues here: 1) people with no clue what an IRC channel is there for 2) people that have no clue that if there is nobody in the channel you will get no answer and 3) the one you stated that it is hardly used.

**Comment by JeroenDeDauw** [comment]
`4)` for whatever reason the CI is still spamming the channel even though we disabled this in the travis config some time back.

**Comment by kghbln** [comment]
After I de-advertised the channel and also added some clarification on the docu page such incidents appear not to have happened again. I'd still like to keep the channel as a quaint way of getting in touch ad-hoc. Since @JeroenDeDauw basically abstained there is no majority for closing.
