### ISSUE TITLE
Reboot server

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#42]
@JeroenDeDauw On Tuesday or Wednesday we will be getting updates for Ubuntu (I wonder why;) that will require a reboot of the server. Once I have done the `dist-upgrade` I will ping you via this issue. It will be great if you could reboot thereafter. Hope you are in town!

**Comment by kghbln** [comment]
Further reading:
- https://usn.ubuntu.com/usn/usn-3522-1/ --> linux-image-generic 4.4.0.108.113
- https://usn.ubuntu.com/usn/usn-3522-3/ --> linux-image-generic 4.4.0.109.114

@JeroenDeDauw I updated the server to "linux-image-generic 4.4.0.109.114" All that is left to do is rebooting the machine and hope that it actually does. It will be nice if you could do this and close this issue thereafter. Thanks a bunch!

**Comment by JeroenDeDauw** [comment]
Just seeing this now. I'm about to go to sleep, so not doing stuff today.

Why are you asking me to do the reboot? If you can do the dist upgrade you can also reboot no? Something wrong with `sudo reboot`? This is what I do on my VPSes :)

**Comment by kghbln** [comment]
> Why are you asking me to do the reboot?

Me too, I am asking you because I believe that here the VM must be restarted via some customer panel provided by Hetzner. That's what we had to do last time so ...

**Comment by kghbln** [comment]
I will try to do the reboot tomorrow morning when you are around. If it does not work or something goes wrong you will be there to help the cause, yes?

**Comment by JeroenDeDauw** [comment]
AFAIK there is no reason to use the Hetzner panel and I suspect it is better to let the VM shut itself down.

**Comment by kghbln** [comment]
Ah, ok. I was not absolutely sure. You never know. So I just rebooted and everything is expectedly in fluffy. Basically you get into action if the VM is not responding.
