### ISSUE TITLE
Upgrade to Bionic Beaver (18.04 LTS) 

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#46]
Ubuntu 18.04 LTS was released last week. This is a tracking issue for upgrading the server. Since it serves with PHP 7.2 I will do the upgrade in October 2018 earliest and December 2018 latest, at least that's my plan.

https://packages.ubuntu.com/bionic/

**Comment by kghbln** [comment]
At the same time it makes sense to upgrade the wiki which needs to move on to the next LTS 1.31 anyways. Sandbox has not fallen apart so far: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3163 and PHP 7.2 issues were [tackled](https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?q=PHP+7.2&type=Issues), too provided that I switch to master SMW.

**Comment by kghbln** [comment]
Now that I have updated the wiki to LTS 1.31 and SMW 3.0.0 this issue is getting more and more close to being done.

**Comment by JeroenDeDauw** [comment]
![image](https://user-images.githubusercontent.com/146040/48866381-ed014a80-edd2-11e8-8087-bd2092f641d8.png)

**Comment by kghbln** [comment]
This is getting urgent now:

**Action required: Let's Encrypt certificate renewals**

Hello,

Action may be required to prevent your Let's Encrypt certificate renewals
from breaking.

If you already received a similar e-mail, this one contains updated
information.

Your Let's Encrypt client used ACME TLS-SNI-01 domain validation to issue
a certificate in the past 60 days. Below is a list of names and IP
addresses validated (max of one per account):

 doc.semantic-mediawiki.org (78.47.118.255) on 2018-12-04

TLS-SNI-01 validation is reaching end-of-life. It will stop working
temporarily on February 13th, 2019, and permanently on March 13th, 2019.
Any certificates issued before then will continue to work for 90 days
after their issuance date.

You need to update your ACME client to use an alternative validation
method (HTTP-01, DNS-01 or TLS-ALPN-01) before this date or your
certificate renewals will break and existing certificates will start to
expire.

Our staging environment already has TLS-SNI-01 disabled, so if you'd like
to test whether your system will work after February 13, you can run
against staging: https://letsencrypt.org/docs/staging-environment/

If you're a Certbot user, you can find more information here:
https://community.letsencrypt.org/t/how-to-stop-using-tls-sni-01-with-certbot/83210

Our forum has many threads on this topic. Please search to see if your
question has been answered, then open a new thread if it has not:
https://community.letsencrypt.org/

For more information about the TLS-SNI-01 end-of-life please see our API
announcement:
https://community.letsencrypt.org/t/february-13-2019-end-of-life-for-all-tls-sni-01-validation-support/74209

Thank you,
Let's Encrypt Staff

**Comment by kghbln** [comment]
Luckly the cert renewal was just due so I gained time until beginning of April. Since I do not have much time this and next weekend I will have to do this on the 17.02.

**Comment by kghbln** [comment]
Will now be done through a move to a bionic server. #52
