### ISSUE TITLE
Consider Hetzner Cloud for hosting

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#47]
Today Hetzner announced its new clound hosting service: https://cloud.hetzner.com/

Probably it is worth considering to change to this when doing https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/46

**Comment by JeroenDeDauw** [comment]
Is there a big advantage of switching? There is some hassle in doing so, including ODSA approval since it affects the payments.

**Comment by kghbln** [comment]
They claim between the lines to abandon the existing hosting options in the long run in favour of this one. In the end it is currently more a benefit for them platformwise than for us. These solutions seem to be cheaper in the end so this is to consider, too. Since they just rolled out this new option we could probably wait another two years and see how things are. Do not want to end up as a testing bunny form them.

**Comment by kghbln** [comment]
Let's revisit this in one or two years. Closing for now.
