### ISSUE TITLE
CAPTCHA is missing on the çreate account page in the sandbox.

### ISSUE THREAD

**Issue by fzand** [SemanticMediaWiki/semantic-mediawiki.org#50]
https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Cr%C3%A9er_un_compte&returnto=Main+Page

**Comment by kghbln** [comment]
Thanks a lot for reporting!

I was experimenting with an new MediaWiki security feature provided via `$wgCSPHeader` which shipped with 1.32.0. This resulted in the following because of a wrong configuration:

```
index.php?title=Spécial:Créer_un_compte&returnto=Main+Page:1 Refused to load the script 'https://www.google.com/recaptcha/api.js?hl=fr' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self' 'nonce-ru6jyt2bKODJbq/ASSqF' 'unsafe-inline' www.semantic-mediawiki.org".
```
This is fixed now.
