### ISSUE TITLE
Move sandbox away from phalaris

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#51]
I have had enough. I have spent the past hour trying to mitigate what cannot be mitigated. sandbox has seen several waves of DOS attacks recently which the server obviously cannot handle. Well the server is not meat to do so actually.

@mwjames @JeroenDeDauw FYI

**Comment by JeroenDeDauw** [comment]
Currently sandbox runs on one of your private servers right? Or is it on some OSDA server?

**Comment by kghbln** [comment]
> Currently sandbox runs on one of your private servers right?

Yes, OSDA is not involved here.

**Comment by kghbln** [comment]
This is done now. All what is missing is the change of the DNS entries. I will now disable the current sandbox.

After the DNS was changed I will switch the wiki to https and do final tweaks.

**Comment by JeroenDeDauw** [comment]
I added the highlighted line. Hope that is what needed to happen

![image](https://user-images.githubusercontent.com/146040/55676572-a589df80-58d7-11e9-9ee4-93ec65ab883e.png)

**Comment by kghbln** [comment]
@JeroenDeDauw I was wondering why the ping still comes from the old server. The change was done only for one subdomain I apparently also totally forgot about: 

- [x] sandbox.semanticmediawiki.org
- [x] sandbox.semantic-mediawiki.org

**Comment by kghbln** [comment]
The DNS change can now also be done for 

- [x] doc.semantic-mediawiki.org
- [x] www.semantic-mediawiki.org
- [x] www.semanticmediawiki.org

I do not think that it is necessary to create a subdomain to semanticmediawiki.org here.

**Comment by JeroenDeDauw** [comment]
Eh. I don't know where semantic-mediawiki.org is registered. These are the ones on Hetzner OSDA account:

![image](https://user-images.githubusercontent.com/146040/55681526-a6e2f880-5927-11e9-8d1f-30d243156bc7.png)

@mkroetzsch do you know where semantic-mediawiki.org is registered and who can access it? We need to update the DNS configuration.

**Comment by kghbln** [comment]
I am a bit surprised as well as amazed. Anyways that's what whois says:
```
whois semantic-mediawiki.org
Domain Name: SEMANTIC-MEDIAWIKI.ORG
Registry Domain ID: D148951761-LROR
Registrar WHOIS Server: whois.udag.net
Registrar URL: https://www.united-domains.de/whois-suche
Updated Date: 2019-02-26T05:23:13Z
Creation Date: 2007-08-24T12:42:38Z
Registry Expiry Date: 2019-08-24T12:42:38Z
Registrar Registration Expiration Date:
Registrar: united-domains AG
Registrar IANA ID: 1408
Registrar Abuse Contact Email: abuse@united-domains.de
Registrar Abuse Contact Phone: +49.8151368670
Reseller:
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Registrant Organization:
Registrant State/Province:
Registrant Country: DE
Name Server: NS.UDAG.ORG
Name Server: NS.UDAG.NET
Name Server: NS.UDAG.DE
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form https://www.icann.org/wicf/)
>>> Last update of WHOIS database: 2019-04-07T09:26:07Z <<<
```
"clientTransferProhibited" is something that worries me. So there was some activity in connection with the domain during the past 60 days? Why is there no registrant recorded?

**Comment by kghbln** [comment]
So I have to move forward moving www.s-mw.org to not end up changing DNS every second day. Looks like a nice Sunday for me. ;)

**Comment by kghbln** [comment]
For the time being sandbox is available [here](http://sandbox.semanticmediawiki.org/wiki/Main_Page)

**Comment by JeroenDeDauw** [comment]
PHP 7.2 but no Maps 8.0? I demand Maps 8.0! :)

**Comment by kghbln** [comment]
> PHP 7.2 but no Maps 8.0? I demand Maps 8.0! :)

PHP 7.2 only matches with Maps 7.2, not sure if this is a hard dependency :P

**Comment by JeroenDeDauw** [comment]
All you need to do is travel to the future where Maps 8.0 exists, get a copy, come back, and install it. Is that really too much to ask?!

**Comment by kghbln** [comment]
So I also moved www to the new server. Still have to create the virtual host, but I will do this in a couple of hours.

**Comment by kghbln** [comment]
www is on the new server for good.
