### ISSUE TITLE
Switch to a new and stronger server

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#52]
In the light of #51 and the fact that "hades" will be decommissioned end of April and that I could avoid having to upgrade the existing server "stetsonia" (#46) I think a restart is possible and actually required.

current "stetsonia": CX30 | 2 vCores | 4 GB | 100 GB | 11.90 EUR/net
proposed "sulcorebutia": CX41 | 4 vCores | 16 GB | 160 GB | 15.90 EUR/net

My private server "phalaris" cannot longer handle sandbox and I have seen situations on "stetsonia" that it shortly ran out of power due to the load. Since the new server should also handle Elasticsearch we need more RAM anyways. All of this combined made me come up with this idea.

Once this is done "stetsonia" could be destroyed immediately.

@JeroenDeDauw @mkroetzsch for your comments, moreover I would need your assistance since I have no access to the OSDA account at Hetzner.

@mwjames FYI

And yes, I like to name servers for better reference. ;)

**Comment by JeroenDeDauw** [comment]
This has my approval though I fear an OSDA vote will be needed

**Comment by kghbln** [comment]
> This has my approval though I fear an OSDA vote will be needed

I do not think so since we are talking about daily operations. Will have a look at the Satzung.

**Comment by mwjames** [comment]
> My private server "phalaris" cannot longer handle sandbox and I have seen situations on "stetsonia" that it shortly ran out of power due to the load. 
> @mwjames FYI

In light of issues (#51) outlined by @kghbln for the current infrastructure, I do hope this issue gets resolved rather quickly and doesn't involve a lot of financial politics behind closed doors.

I appeal to responsible persons (including @mkroetzsch) to make decisions in an appropriate time frame without me having to come back on this due to lack of progress.

**Comment by kghbln** [comment]
> I appeal to responsible persons (including @mkroetzsch) to make decisions in an appropriate time frame without me having to come back on this due to lack of progress.

I am working on this with priority now.

**Comment by mkroetzsch** [comment]
I fully agree with the proposed change. Thanks, Karsten, for taking care of this.

I think it is not necessary to have an OSDA vote for this, since it seems clear that this is needed and wanted, and it is also cheaper than what we pay now. Even compared to the current main server, the price increase amounts to just 60EUR per year -- an amount that I am happy to take responsibility for ;-)

**Comment by JeroenDeDauw** [comment]
Don't forget we also have an older server... I think that one has just the OSDA site on it?

![image](https://user-images.githubusercontent.com/146040/54469290-64018b00-4796-11e9-944c-deb423a47c2b.png)

**Comment by JeroenDeDauw** [comment]
The price I get on the ordering page is higher than that on the homepage. The ordering page says it includes VAT, so perhaps that is the difference? Are we still OK with the 18.92 EUR price?

![image](https://user-images.githubusercontent.com/146040/54469393-a24b7a00-4797-11e9-9305-27423dc3bd72.png)

**Comment by JeroenDeDauw** [comment]
Currently we pay 16.72 EUR for the VQ19 and 11.9 for the CX30 (numbers coming from the invoices)

**Comment by kghbln** [comment]
> The ordering page says it includes VAT, so perhaps that is the difference? 

Indeed that's the difference. So nothing to worry here.

> Currently we pay 16.72 EUR for the VQ19 and 11.9 for the CX30 (numbers coming from the invoices)

That's true but both will be gone by the end of the month. I will ask you to destroy both VM after I migrated all the stuff.

**Comment by kghbln** [comment]
> I think that one has just the OSDA site on it?

That's true. Since I still cannot access I will ask you to create a new account for me. The old account of me on that server is blocked so new passes will not help me here.

**Comment by JeroenDeDauw** [comment]
![image](https://user-images.githubusercontent.com/146040/54484989-756b9580-4871-11e9-9543-ffd8200e0e43.png)

![image](https://user-images.githubusercontent.com/146040/54485067-b44e1b00-4872-11e9-9ae8-2bdf7521e4d2.png)

**Comment by JeroenDeDauw** [comment]
![image](https://user-images.githubusercontent.com/146040/54485111-730a3b00-4873-11e9-9351-89056e5292fd.png)

I have not installed ANYTHING yet. Only stuff I did was create kghbln account and add the public key there.

Let me know if I forgetti'd something or otherwise fucked up

**Comment by kghbln** [comment]
> I have not installed ANYTHING yet. Only stuff I did was create kghbln account and add the public key there.

I will do the rest.

> Let me know if I forgetti'd something

Yeah. I logged onto the server but I still need to be able to sudo. So allowing me to sudo an create a password for it will be cool. Just put it into a file in my home directory.

> And yes, I like to name servers for better reference. ;)

Aren't they pretty: e.g. [Sulcorebutia arenacea](https://upload.wikimedia.org/wikipedia/commons/b/bf/Sulcorebutia_arenacea_MC4400.jpg)

**Comment by JeroenDeDauw** [comment]
Right, multiple forgetti's :) I did create the account with a password though then forgetti'd to share it. Now in ~/pw.txt. Also gave you sudo

**Comment by JeroenDeDauw** [comment]
uuugh. Also going to disable ssh login via password now... done

**Comment by kghbln** [comment]
I will do this this afternoon. First I will move sb.s-mw.o and this is up and running I will move s-mb.o

**Comment by JeroenDeDauw** [comment]
Uh oh, seems like we have a deadline 

![image](https://user-images.githubusercontent.com/146040/55676528-3b713a80-58d7-11e9-9d76-fab80ce01fee.png)

**Comment by kghbln** [comment]
> Uh oh, seems like we have a deadline

@JeroenDeDauw Indeed, however only for hades which is the ante-diluvian server still running Debian 6 [ouch].

Talking of which: I am still locked out via my rebular accout. Thus it will be great if you could create a new user e.g. bunny for me and add the same cert as for the very new server.

Still need to move some stuff away from the very old server.

**Comment by kghbln** [comment]
I somehow had hoped that this will be somewhat smooth transition but in the light of the recent domain related findings this is going to be a rodeo.

**Comment by kghbln** [comment]
This really gets on my bloody nerves. When trying to import MySQL 5.7 bull into MariaDB 10 whatever bull I get ```ERROR 1064 (42000) at line 3544: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' special property property name creation date minimum version 1u800u82e7u800u82' at line 1```
Now I end up editing the dump. What's what I have always wished for. 

https://stackoverflow.com/questions/18742492/error-1064-42000-you-have-an-error-in-your-sql-syntax

**Comment by kghbln** [comment]
We have progress here however I am pretty slow since I have to learn quite a lot en passant to make it right. In the end I fond not only one but three wikis on "hades" which need to be migrated, one as wiki to wiki and two as wiki to html. I guess we can initiate the DNS changes for all website still served via hades tomorrow.

**Comment by mkroetzsch** [comment]
I have now updated the DNS again as requested, but there is an error (sulcorebutia does not seem to handle semantic-mediawiki.org but shows a default page). Should I switch back?

**Comment by kghbln** [comment]
> I have now updated the DNS again as requested, but there is an error (sulcorebutia does not seem to handle semantic-mediawiki.org but shows a default page). Should I switch back?

No, I will have a look right away. Probably I just have forgotten to activate the VirtualHost or so though I figured I had.

**Comment by kghbln** [comment]
> Probably I just have forgotten to activate the VirtualHost or so though I figured I had.

Indeed. Unbelievable, I activated everything but this one. Senior moments. Lucky me I just checked my mailbox.

**Comment by kghbln** [comment]
@mkroetzsch @JeroenDeDauw I will inform you on this issue as soon as the old server may be destroyed.

**Comment by kghbln** [comment]
@mkroetzsch Thanks a lot for changing the DNS!

**Comment by kghbln** [comment]
This is done.
