### ISSUE TITLE
Setup backups to external host

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#57]
Currently sandbox was backing up to the www host and vice versa. I need to change this from sandbox and www host to phalaris which was formerly holding sandbox.

**Comment by JeroenDeDauw** [comment]
All your datas are belong to ... bunny

![image](https://user-images.githubusercontent.com/146040/55682969-8a9c8700-593a-11e9-8c6d-9d3c087b85c2.png)

**Comment by kghbln** [comment]
Done now for or three wikis.
