### ISSUE TITLE
Main wiki still extremely slow

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/semantic-mediawiki.org#6]
I wanted to poke a bit at the maps docs, but with this speed I need to wait half a minute before a page loads :(

**Comment by kghbln** [comment]
This is an on and off thing at the moment. :|

**Comment by kghbln** [comment]
This is ridiculous. Still some idiot via [IP 62.210.78.104](https://db-ip.com/62.210.78.104) causes this issues in waves.

**Comment by kghbln** [comment]
I have not blocked this IP. Let's see where we go from here.

**Comment by kghbln** [comment]
This seems to have done the job. Server load is now so minimal.

**Comment by JeroenDeDauw** [comment]
\o/ The server is now totally @kghbln fluffy again!

![fast-rabbit-run](https://cloud.githubusercontent.com/assets/146040/16362313/3d97b7b2-3bac-11e6-9f66-b0c4d1486e46.jpg)

**Comment by kghbln** [comment]
Cool for now. In case of new issues ...
