### ISSUE TITLE
Google verification in DNS

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/semantic-mediawiki.org#60]
@mkroetzsch can you add this DNS record for semantic-mediawiki.org? Then we can see the search info google collects on our site.

    @                        IN TXT     "google-site-verification=0Z4HlcBWnKJJxJD-uvaIIp_whBP9jrD0YuPyORENdJs"

**Comment by mkroetzsch** [comment]
I have done that just now. If you can, please verify that it works.

**Comment by JeroenDeDauw** [comment]
Yes it works. If you want me to add you to the search console, please tell me which of your emails to use @mkroetzsch @kghbln

**Comment by JeroenDeDauw** [comment]
(Needs to be a google account email I believe)

**Comment by kghbln** [comment]
> Yes it works. If you want me to add you to the search console, please tell me which of your emails to use @mkroetzsch @kghbln

> (Needs to be a google account email I believe)

@JeroenDeDauw Try this one: mediawiki@kghoffmeyer.de

**Comment by kghbln** [comment]
@JeroenDeDauw 

You can inform Google about our [sitemap](https://www.semantic-mediawiki.org/s/sitemap-index-semantic-mediawiki.xml)

**Comment by JeroenDeDauw** [comment]
That sitemap was submitted on April 16th, which is before I got access to the search console. Not sure if someone else had/has access somehow and added it, or if google found it and submitted it itself.

**Comment by kghbln** [comment]
> That sitemap was submitted on April 16th, which is before I got access to the search console. Not sure if someone else had/has access somehow and added it, or if google found it and submitted it itself.

Probably Google found and submitted automatically since I added the location to [robots.txt](https://www.semantic-mediawiki.org/robots.txt)

@JeroenDeDauw I assume that we are talking about the Semantic MediaWiki account at Google. Admittedly I am listed as someone with access to it however I lost the credentials. If you could ...

**Comment by JeroenDeDauw** [comment]
There is no credentials for this, just your Google Account

![image](https://user-images.githubusercontent.com/146040/57569576-223c3c00-73f7-11e9-91bc-686a7ba1566f.png)

**Comment by kghbln** [comment]
Ah, thanks for the re-vaccination. I was unaware. Have not used this Google account in years. After some investigation I was able to find the credentials for it. :) PS Guess what else I found. :)

**Comment by JeroenDeDauw** [comment]
Well it is the account you suggested a few comments above :D

![image](https://user-images.githubusercontent.com/146040/57570304-b4950d80-7400-11e9-884d-5108f296953c.png)

> Guess what else I found. :)

A 1000 bitcoin wallet?

**Comment by kghbln** [comment]
> Well it is the account you suggested a few comments above :D

Sometimes I truly amaze myself. Probably I meant adding this e-mail address to the addresses that may access the smw account at Google. Whatever, it is all happening. Had to fix the link to the sitemap since I moved it around last month.
