### ISSUE TITLE
"DisplayTitleHooks.php": Call to a member function isTalkPage() on null

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#63]
### Setup
- MediaWiki 	1.33.0 (1c47e93) 15:49, 16. Jul. 2019
- PHP 	7.2.19-0ubuntu0.18.04.1 (apache2handle
- MariaDB 	10.1.40-MariaDB-0ubuntu0.18.04.1
- DisplayTitle	2.0.0 (0705659) 14:51, 6. Feb. 2019

refs: https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Requ%C3%AAter&#search

### Issue

```
[ddc4653e9eff034859c5f6dc] /w/index.php?title=Sp%C3%A9cial:Requ%C3%AAter& Error from line 183 of /var/www/html/sbxsmw/w/extensions/DisplayTitle/includes/DisplayTitleHooks.php: Call to a member function isTalkPage() on null
```

### Backtrace:
```
#0 /../w/includes/Hooks.php(174): DisplayTitleHooks::onParserBeforeStrip(Parser, string, NULL)
#1 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#2 /../w/includes/parser/Parser.php(695): Hooks::run(string, array)
#3 /../w/extensions/SemanticResultFormats/formats/graphviz/SRF_Graph.php(136): Parser->recursiveTagParse(string)
#4 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(342): SRFGraph->getResultText(SMW\Query\QueryResult, integer)
#5 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(307): SMW\Query\ResultPrinters\ResultPrinter->buildResult(SMW\Query\QueryResult)
#6 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(481): SMW\Query\ResultPrinters\ResultPrinter->getResult(SMW\Query\QueryResult, array, integer)
#7 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(316): SMW\MediaWiki\Specials\SpecialAsk->fetchResults(SRFGraph, SMWQuery, SMW\MediaWiki\Specials\Ask\UrlArgs)
#8 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(169): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#9 /../w/includes/specialpage/SpecialPage.php(569): SMW\MediaWiki\Specials\SpecialAsk->execute(NULL)
#10 /../w/includes/specialpage/SpecialPageFactory.php(558): SpecialPage->run(NULL)
#11 /../w/includes/MediaWiki.php(288): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#12 /../w/includes/MediaWiki.php(865): MediaWiki->performRequest()
#13 /../w/includes/MediaWiki.php(515): MediaWiki->main()
#14 /../w/index.php(42): MediaWiki->run()
#15 {main}
```

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by kghbln** [comment]
> FYI

Thanks for the note. Reported with [task T228595.](https://phabricator.wikimedia.org/T228595)

**Comment by kghbln** [comment]
@mwjames I checked out the patch on sandbox. Could you please check if this fixes the issue? Admittedly I was not able to create the stacktrace form the link provided so I just trusted you on this one when reporting.

**Comment by mwjames** [comment]
> @mwjames I checked out the patch on sandbox. Could you please check if this
> fixes the issue? Admittedly I was not able to create the stacktrace form the
> link provided so I just trusted you on this one when reporting.

You just need:

- Condition `[[Has number::+]]`
- Printout: `Has number`
- Format: `graph`

The `DisplayTitle` issue is gone but now you get:

```
[9889623253b9e362dfc78301]
/w/index.php?title=Sp%C3%A9cial:Requ%C3%AAter& Error from line 52 of
/../w/extensions/Translate/tag/PageTranslationHooks.php:
Call to a member function getIsSectionPreview() on null

Backtrace:

#0 /../w/includes/Hooks.php(174):
PageTranslationHooks::renderTagPage(Parser, string, NULL)
#1 /../w/includes/Hooks.php(202):
Hooks::callHook(string, array, array, NULL)
#2 /../w/includes/parser/Parser.php(695):
Hooks::run(string, array)
#3 /../w/extensions/SemanticResultFormats/src/Graph/GraphPrinter.php(152):
Parser->recursiveTagParse(string)
#4 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(342):
SRF\Graph\GraphPrinter->getResultText(SMW\Query\QueryResult, integer)
#5 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(307):
SMW\Query\ResultPrinters\ResultPrinter->buildResult(SMW\Query\QueryResult)
#6 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(481):
SMW\Query\ResultPrinters\ResultPrinter->getResult(SMW\Query\QueryResult,
array, integer)
#7 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(316):
SMW\MediaWiki\Specials\SpecialAsk->fetchResults(SRF\Graph\GraphPrinter,
SMWQuery, SMW\MediaWiki\Specials\Ask\UrlArgs)
#8 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(169):
SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#9 /../w/includes/specialpage/SpecialPage.php(569):
SMW\MediaWiki\Specials\SpecialAsk->execute(NULL)
#10 /../w/includes/specialpage/SpecialPageFactory.php(558):
SpecialPage->run(NULL)
#11 /../w/includes/MediaWiki.php(288):
MediaWiki\Special\SpecialPageFactory->executePath(Title,
RequestContext)
#12 /../w/includes/MediaWiki.php(865):
MediaWiki->performRequest()
#13 /../w/includes/MediaWiki.php(515): MediaWiki->main()
#14 /../w/index.php(42): MediaWiki->run()
#15 {main}

```

The `PageTranslationHooks` hook has the same underlying issue which is
that it isn't gated against a NULL title.

**Comment by kghbln** [comment]
@mwjames Thanks for your swift reply. I will report the issue as fixed for DisplayTitle and will report an now one for Translate. Eventually paradise will be regained.

> - Condition `[[Has number::+]]`  - Printout: `Has number` - Format: `graph`

Ah, and I thought just calling the page would create the issue.

**Comment by kghbln** [comment]
Reported with [T228881.](https://phabricator.wikimedia.org/T228881)

**Comment by cicalese** [comment]
I ran the two issues by one of our engineers to try to get at the root cause. The response: "I'd look for a code path that is getting into those hooks without having triggered a call to `Parser->startParse()`. I see both bugs include a call from "extensions/SemanticResultFormats" to `Parser->recursiveTagParse(string)` downstream of SMW's "Special:Ask"; probably someone involved in one of those two components either forgot to call `Parser->startExternalParse()` or is incorrectly calling some code that is intended to be called only from parser hooks."

In each of the stack traces, I find a line of the form:
`
$result = $GLOBALS['wgParser']->recursiveTagParse( "<graphviz>$graphInput</graphviz>" );
`
in SemanticResultFormats (at SemanticResultFormats/formats/graphviz/SRF_Graph.php" (136) and "SemanticResultFormats/src/Graph/GraphPrinter.php" (152)). Perhaps adding a call to `$GLOBALS['wgParser']->startExternalParse(...)` before those lines would help?

**Comment by kghbln** [comment]
@cicalese Thanks for digging into this and notifying us here. Lucky us the "graph" format is currently being refactored (https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/503), this I will notify folks of your findings to add this further improvement for the future.

**Comment by mwjames** [comment]
>
> $result = $GLOBALS['wgParser']->recursiveTagParse(
> "<graphviz>$graphInput</graphviz>" );

This was introduced by [0] in Jan 2018 as replacement for
`GraphViz::graphvizParserHook( $graphInput, "", $GLOBALS['wgParser'],
"" )`.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/365

> Parser->recursiveTagParse(string) downstream of SMW's SpecialAsk; probably
> someone involved in one of those two components either forgot to call
> Parser->startExternalParse() or is incorrectly calling some code that is
> intended to be called only from parser hooks."

I have to say that I'm a bit surprised by this suggestion (meaning to
use `startExternalParse` prior) because I never heard of this before
that such call is required in connection with `recursiveTagParse` and
the documentation [1] doesn't hint any of this as being a hard
requirement to the call of `recursiveTagParse`.

My interpretation of [1] was that when calling
`Parser::recursiveTagParse` (or for that matter
`recursiveTagParseFully`) I get a HTML output (safe or unsafe) without
being required to create a `Title` instance, handle a `ParserOptions`
instance or think about some `$outputType`.

Any extension hooking into the `Parser` is likely to encounter a
situation where a Title instance is `null` and as such one should gate
against those cases because it is unlikely that all users of
`recursiveTagParse` will have heard of calling `startExternalParse`
prior the mentioned `recursiveTagParse` or `recursiveTagParseFully`.

If you think a `Title` instance needs to be present while calling
`recursiveTagParse` then the `Parser` should add an explicit check and
extend the documentation [1] for developers that are unfamiliar with
the Parser instance invocation or its object dependencies.

[1] https://github.com/wikimedia/mediawiki/blob/9aeea7989766f2fec8920510ea8815aa403f9edb/includes/parser/Parser.php#L733-L757

**Comment by cicalese** [comment]
Agreed that if there is a dependency upon Parser->startExternalParse(), it should be documented. It would be good to know if adding that does indeed help your situation or whether there is some other root cause. If it does help, we could propose a change to the documentation to indicate that. Otherwise, we would still need to look further for a root cause. I initially was wondering whether the fact that the code is invoked from a special page when the problem manifests itself is material, but perhaps that is not related.

**Comment by mwjames** [comment]
> Otherwise, we would still need to look further for a root cause. I initially
> was wondering whether the fact that the code is invoked from a special page
> when the problem manifests itself is material, but perhaps that is not
> related.

From my quick inspection of [0], I think this assumption is hitting a
mark given those embedded in a wiki page do display correctly without
an exception meaning the use of `Parser::recursiveTagParse` is
inconsistent when it comes to the context of its execution.

[0] https://sandbox.semantic-mediawiki.org/w/index.php?title=Attribut%3AQuery+format&limit=20&offset=0&filter=graph

**Comment by SbstnS** [comment]
@cicalese As I'm working on the graph format I've tried to add the `$GLOBALS['wgParser']->startExternalParse(...)` before calling the `$GLOBALS['wgParser']->recursiveTagParse()` [0] as you recommended but now it won't render the parser function anymore instead it prints out the raw syntax of graphViz.

//GraphPrinter.php [0]
```
$GLOBALS['wgParser']->startExternalParse(null, ParserOptions::newFromUser( $GLOBALS['wgUser'] ), Parser::OT_WIKI );

// Calls graphvizParserHook function from MediaWiki GraphViz extension
$result = $GLOBALS['wgParser']->recursiveTagParse( "<graphviz>$graphInput</graphviz>" );`
```

With this approach I also get an error when calling the graph format under the "Special:Ask" page.

**Comment by cicalese** [comment]
@RacoonDev I'm wondering if the reason it is not rendering the parser function is that you are passing in Parser::OT_WIKI rather than Parser::OT_HTML.

Is the error you are getting related to the title being null? Did you try passing in the Title object rather than null for the first parameter?

**Comment by cicalese** [comment]
@mwjames 

> From my quick inspection of [0], I think this assumption is hitting a mark given those embedded in a wiki page do display correctly without an exception meaning the use of `Parser::recursiveTagParse` is inconsistent when it comes to the context of its execution.

Agreed. Perhaps there is something different in the way the Parser object is constructed for special pages.

**Comment by kghbln** [comment]
The fix probably caused https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4330

**Comment by mwjames** [comment]
> The fix probably caused
> https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4330

The issue here is different (I will comment there) but it scratches
the same operational surface.

**Comment by kghbln** [comment]
Fixed last year with https://gerrit.wikimedia.org/r/525191
