### ISSUE TITLE
Semantic Title issue

### ISSUE THREAD

**Issue by Omaniac** [SemanticMediaWiki/semantic-mediawiki.org#64]
Hi,

Where can i post issues with Semantic Title / Display Title?

I get this error, and the page_props table is not populated with DISPLAYTITLE content...

[installdir]/extensions/SemanticTitle/SemanticTitleHooks.php: Undefined class constant 'TYPE_STRING'

Regards,
Paal

**Comment by JeroenDeDauw** [comment]
SemanticTitle is not supported by the people here on GitHub. Development is happening on Wikimedia Gerrit which means issues are tracked _somewhere_ on Wikimedia Phabricator https://phabricator.wikimedia.org/

These people created the extension though I am not sure it is actively maintained: https://github.com/wikimedia/mediawiki-extensions-SemanticTitle/blob/master/SemanticTitleHooks.php#L3-L4

**Comment by kghbln** [comment]
The "Semantic Title" extension was [archived today](https://www.mediawiki.org/w/index.php?title=Extension%3ASemantic_Title&type=revision&diff=3339093&oldid=3000491), probably as a result of this post. Not absolutely sure, though. Anyways, kick "Semantic Title" an use "DisplayTitle" instead.
