### ISSUE TITLE
Header Tabs causing JS errors

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/semantic-mediawiki.org#66]
Seeing occasional errors in the browser console

Looks like there where some fixes to Header Tabs already but no release. Can we just pull the latest master? I think that was already done before since latest release is from 2017 and we running 2019 code.

**Comment by JeroenDeDauw** [comment]
OR... if we are not using Header Tabs, then just ditch the thing?

**Comment by kghbln** [comment]
> OR... if we are not using Header Tabs, then just ditch the thing?

To my regret this is still a system relevant extension. We use it on several spots so we cannot ditch.

> Seeing occasional errors in the browser console

Please check if the errors persist now what HeaderTabs is running current master

**Comment by JeroenDeDauw** [comment]
Seems fixed
