### ISSUE TITLE
Switch to AWS SES for mail delivery

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#67]
I think it will be best to switch e-mail delivery to a mailing service rather than trying to maintain a mail server for the two wikis.

@JeroenDeDauw I think this will be save to do?

**Comment by JeroenDeDauw** [comment]
Is there a problem with the mail server?

**Comment by kghbln** [comment]
Try to make an educated guess. :)

**Comment by JeroenDeDauw** [comment]
How urgent is this then?

**Comment by kghbln** [comment]
I think this should be done this or next week.

**Comment by kghbln** [comment]
@JeroenDeDauw This completely ruined my day. Do I need to provide payment details to get this working? I really must deal with this after my return.

**Comment by JeroenDeDauw** [comment]
Missing some context here. Are you creating a new Amazon Web Services account for SMW stuff? Are you using the Professional Wiki account?

**Comment by JeroenDeDauw** [comment]
I'm currently not sure how to log into the SMW server btw. Too many credentials for Hetzner and their multiple places to login are not helping. URL to the place to log in plus the username would probably unconfuse me.

**Comment by kghbln** [comment]
> Missing some context here. Are you creating a new Amazon Web Services account for SMW stuff? Are you using the Professional Wiki account?

No, I was thinking of using a new account for smw. However we as PW could sponsor this. If using PW I know what to do.

**Comment by JeroenDeDauw** [comment]
Lets use my private account instead. It is already setup. I'll send you the SMTP credentials later.

**Comment by JeroenDeDauw** [comment]
DNS stuff needs updating:

**Domain Verification Record**

_amazonses.semantic-mediawiki.org TXT 7u+nNHFnb3sJARN9wJ8DwFZBcLgvCjqhLz0XcGWFQHg=

**DKIM Record Set**
nfxtv22c5irjcvcfiu4cx2bng3v2mm7t._domainkey.semantic-mediawiki.org CNAME nfxtv22c5irjcvcfiu4cx2bng3v2mm7t.dkim.amazonses.com

ab4tnyzz3ypiffdiqngc7fbb2wbijsgz._domainkey.semantic-mediawiki.org CNAME ab4tnyzz3ypiffdiqngc7fbb2wbijsgz.dkim.amazonses.com

ymg4k43pxj6465s7djmr72wubox2omiz._domainkey.semantic-mediawiki.org CNAME ymg4k43pxj6465s7djmr72wubox2omiz.dkim.amazonses.com

**Comment by JeroenDeDauw** [comment]
@kghbln  I've send you the SMTP credentials

**Comment by kghbln** [comment]
SCHEISSE, SCHEISSE, SCHEISSE. WTBF. 

@JeroenDeDauw s-mw.o is not controlled by OSDA. We need to switch to semanticmediawiki.org which is since I have no interest to follow up on s-mw.o. smw.o is good enough for me. Could you initiate verification for smw.o? This is so bloody exhausting for me. Really.

I got the credentials. I assume that I can reuse them for smw.o

**Comment by mkroetzsch** [comment]
I am afraid I cannot extract from the posts what this thread is about, nor why Karsten is loosing his composure over it. But if there is any problem related to the domain registry of semantic-mediawiki.org, I might be able to help.

**Comment by kghbln** [comment]
This is about making e-mail delivery more reliable. In the meantime gmail rejects e-mails from the wiki prior to delivery, i.e. the recipient receives nothing. Unfortunately a lot of people use gmail for whatever reason I yet fail to grasp. Anyways Amazon SES provides a mail delievery service which allows sending e-mails without the hassle of maintaining a mail server. To verify that we control the domain we need to add DNS records.

This is an example how the result looks in a DNS record for e.g. example.com:

![Bildschirmfoto vom 2019-10-07 10-56-16](https://user-images.githubusercontent.com/1104078/66298471-201cd180-e8f2-11e9-80fe-75c7e3edc245.png)

Jeroen posted the data to be added in his post.

**Comment by JeroenDeDauw** [comment]
@mkroetzsch can you add [these 4 DNS records](https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/67#issuecomment-536105723) for semantic-mediawiki.org? If not we can set up emails via semanticmediawiki.org, though that is not quite as nice.

**Comment by mkroetzsch** [comment]
Ok, I can look into this. Will this affect the working of any email addresses of the form "...@semantic-mediawiki.org" that are currently in use? I now have United Domains forward many such emails (including for my own account).

**Comment by JeroenDeDauw** [comment]
This won't effect existing email addresses. These DNS records just verify that we are not random spammers using semantic-mediawiki.org addresses as sender, and that we instead control the domain.

**Comment by kghbln** [comment]
@JeroenDeDauw It will be great if we could also do this for smw.o to have an alternative.

**Comment by JeroenDeDauw** [comment]
_amazonses.semanticmediawiki.org TXT M9lbcgv9861m8bxQ8Kxr2rswZwHopE0eDx2hYqg14Qo=

rwvetgqmpxkm63edaxer6iqb2rxz7c3b._domainkey.semanticmediawiki.org CNAME rwvetgqmpxkm63edaxer6iqb2rxz7c3b.dkim.amazonses.com

mjodykbdy6tesbijqa7rjurdnve3kg3h._domainkey.semanticmediawiki.org CNAME mjodykbdy6tesbijqa7rjurdnve3kg3h.dkim.amazonses.com

qso32z7eozrzqyzrwmm74r5ulgyxvsmx._domainkey.semanticmediawiki.org CNAME qso32z7eozrzqyzrwmm74r5ulgyxvsmx.dkim.amazonses.com

**Comment by kghbln** [comment]
@JeroenDeDauw Thanks a lot. Added the following:

```
mjodykbdy6tesbijqa7rjurdnve3kg3h._domainkey   300 IN CNAME   mjodykbdy6tesbijqa7rjurdnve3kg3h.dkim.amazonses.com
qso32z7eozrzqyzrwmm74r5ulgyxvsmx._domainkey   300 IN CNAME   qso32z7eozrzqyzrwmm74r5ulgyxvsmx.dkim.amazonses.com
rwvetgqmpxkm63edaxer6iqb2rxz7c3b._domainkey   300 IN CNAME   rwvetgqmpxkm63edaxer6iqb2rxz7c3b.dkim.amazonses.com
_amazonses           300 IN TXT     "M9lbcgv9861m8bxQ8Kxr2rswZwHopE0eDx2hYqg14Qo="
```
Note the quotes added tot th TXT entry which is required by syntax. Without the entry will fail. Also added 300 as TTL for the moment. Can be removed the next days.

It will be nice if you could report back fluff - hopefully.

**Comment by kghbln** [comment]
Obviously I have to edit smw.o and not osda.o :|

**Comment by kghbln** [comment]
Switched to AWS SES with @semanticmediawiki.org. Keeping this open for @semantic-mediawiki.org

**Comment by JeroenDeDauw** [comment]
@mkroetzsch so what is left here is adding [these 4 DNS records](https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/67#issuecomment-536105723) to semantic-mediawiki.org. If you don't have time to manage the domain maybe you can share credentials? (keybase: https://keybase.io/jeroendedauw)

**Comment by kghbln** [comment]
semanticmediawiki.org as sender of e-mails is good enough for me. Once semantic-mediawiki.org is set up I can switch.
