### ISSUE TITLE
@dev no longer with effect

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#81]
After the upgrade, [except for SMW all extensions specified with @dev](https://sandbox.semantic-mediawiki.org/wiki/SMW_Sandbox:Setup_information#composer.local.json) were downgraded to latest stable. We need to figure out why? Currently I have no clue.

**Comment by kghbln** [comment]
Perhaps this helps: https://stackoverflow.com/questions/21154216/composer-wont-install-require-dev-packages Not tried yet.

**Comment by JeroenDeDauw** [comment]
If you need master, use `dev-master`

**Comment by kghbln** [comment]
This is basically specifying the name of the master branch to fetch. I bit sad that I cannot longer use @dev Worked well for over 8 years. Anyhow, will use this.

**Comment by kghbln** [comment]
Indeed, either use `@dev` or `dev-master`, which depends on what you wanna get.
