### ISSUE TITLE
Enable QUnit on sandbox?

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/semantic-mediawiki.org#83]
Can we enable QUnit on https://sandbox.semantic-mediawiki.org to reproduce JS testing / failures?

`$wgEnableJavaScriptTest = true;` to enable https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:JavaScriptTest

**Comment by kghbln** [comment]
@gesinn-it Done. Special page is now functional.
