### ISSUE TITLE
SMW Website: Stop using fancy image display, unless you know it to work in the major browsers.

### ISSUE THREAD

**Issue by MvGulik** [SemanticMediaWiki/semantic-mediawiki.org#84]
The Semantic MediaWiki website never ceases to amaze me.

- Using Firefox.
- Going to page https://www.semantic-mediawiki.org/wiki/Help:Input_assistance
- Clicking on the first image on the page.
- And now I have to close that browser tab, and re-open the "Input_assistance" page in a new tab ... as alternative to just closing the "_Where trying to do some fancy image display here, but we still have not got the hang of it._" image showing stuff.

(_spelling_)

**Comment by kghbln** [comment]
Thanks for reporting and once again being our heart warming ray of sun.

Indeed this is an incompatibility between the `overlay` option to the "gallery" format and MultimediaViewer extension which I have [already documented last year](https://www.semantic-mediawiki.org/w/index.php?title=Help:Gallery_format&diff=76912&oldid=71095) (lucky me). Just did a search and replace to switch the remaining occurrences to "no". Hopefully I picked up all of them.
