### ISSUE TITLE
"_heart warming ray of sun_" here. ...

### ISSUE THREAD

**Issue by MvGulik** [SemanticMediaWiki/semantic-mediawiki.org#85]
"_heart warming ray of sun_" here. ... #84 

![unnamed](https://user-images.githubusercontent.com/666868/115903885-6863fc00-a464-11eb-8597-984c5a1b1b25.jpg)

Immediately locking that topic after fixing & closing it (_other closed topics are not locked. Ergo: it was specific to that topic_). Is exactly not the thing to do in my view, as it seems to me it will only strengthening any negative views on the semantic-mediawiki team one might have. (_It also kinda shows some potential high sensibility in that area. One might wonder why that might be._)

Anyway.
It seems to me that that topic lock ... did not really work as intended.
And needles to say that it did change whatever message I might have wanted to add to it ... if any, that is, of course.

![unnamed2](https://user-images.githubusercontent.com/666868/115905059-dbba3d80-a465-11eb-8412-9bbc9107afbb.jpg) ?
---
lol. No rev back to this topic in ref'ed topic I see. One learns something new every day.

See you in next Issue (_if any that is, as I generally try to stay away of the SMW website as long as I can_).

**Comment by kghbln** [comment]
This is the kind of bulshit I wanted to avoid by locking the issue. Anyhow I won a bet an earned some money.
