### ISSUE TITLE
Update wiki to MW 1.27 LTS branch

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#9]
This should be done after the release of SMW 2.4.0

Current blocker is [T137843](https://phabricator.wikimedia.org/T137843) for the ConfirmAccount extension.

**Comment by kghbln** [comment]
> Current blocker is T137843 for the ConfirmAccount extension.

No more blockers. Will do the upgrade now.

**Comment by kghbln** [comment]
FYI @JeroenDeDauw @mwjames So the upgrade is basically done. Things still need to be done later on:
- [x] Reenable user registration
- [x] Fluff "LocalSettings.php"

I will do these after high tea in about one and a half hours.

The only pain is actually the GitHub extension. Since this is heavily used ...

**Comment by kghbln** [comment]
I had hoped that we could do without ConfirmAccount. Reality cannot be beaten though so back it is.

**Comment by JeroenDeDauw** [comment]
Hopefully fixed by https://github.com/JeroenDeDauw/GitHub/pull/28

**Comment by kghbln** [comment]
> Hopefully fixed by JeroenDeDauw/GitHub#28

We are fully operational again. Thanks a lot! I have now also added this extension to sandbox for earlier grump detection.
